apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
      - name: shoppingclient
        image: kaniacr.azurecr.io/shopping_app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: development
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ApiURL
          valueFrom:
            configMapKeyRef:
              name: "shopping-client-configmap"
              key: API_URL
      imagePullSecrets:
        - name: acr-secret
---

apiVersion: v1
kind: Service
metadata:
  name: shoppingclientservice
spec:
  type: LoadBalancer
  selector:
    app: shoppingclient   
  ports:
  - port: 80
    protocol: TCP

