apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: shoppingapi
        image: kaniacr.azurecr.io/shopping_api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: development
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DatabaseSetting__ConnectionString
          valueFrom:
            configMapKeyRef:
              name: "mongo-config"
              key: connection_string
---

apiVersion: v1
kind: Service
metadata:
  name: shoppingapiservice
spec:
  selector:
    app: shoppingapi
  ports:
  - port: 80
    protocol: TCP

