apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient
spec:
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: shoppingclient
        image: kaniarasan19/shopping_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: development
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ApiURL
          valueFrom:
            configMapKeyRef:
              name: "shopping-client-configmap"
              key: API_URL

---

apiVersion: v1
kind: Service
metadata:
  name: shoppingclientservice
spec:
  selector:
    app: shoppingclient
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001
    protocol: TCP

